name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  uv-version: "0.8.3"

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.uv-version }}
      - name: Test with Nox
        run: uv run --locked nox -s test-${{ matrix.python }}
      - name: Store coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python }}
          path: .coverage.*
          include-hidden-files: true
          if-no-files-found: error

  coverage:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.uv-version }}
      - name: Fetch coverage
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true
      - name: Combine coverage and generate report
        run: uv run --locked nox -s coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  quality:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nox-session: ["lint", "type_check"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.uv-version }}
      - name: Check code quality with Nox
        run: uv run --locked nox -s ${{ matrix.nox-session }}
