name: python

on: [push]

jobs:
  tox:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Nox
        uses: excitedleigh/setup-nox@1.0.0
      - name: Run nox
        run: nox
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: .coverage
